import traceback
from enum import Enum


# from CommonServerPython import CommandResults, return_results, return_error

class Status(Enum):
    SUSPICIOUS = 'Suspicious'
    BENIGN = 'Benign'
    UNKNOWN = 'Unknown'


STATUS_TO_COLOR = {
    Status.SUSPICIOUS: "ðŸ”´",
    Status.BENIGN: "ðŸŸ¢",
    Status.UNKNOWN: "âšª"
}


class Finding:
    question: str
    status: Status

    def __init__(self, context_finding: dict):
        self.name, values = next(iter(context_finding.items()))  # only one item in dict
        self.status = Status(values.get('Status', Status.UNKNOWN.value))

    def to_summary_line(self) -> dict:
        return {
            'Name': self.name,
            'Status': f'{STATUS_TO_COLOR[self.status]} {self.status.value.title()}'
        }


def get_findings(malware_findings_context: tuple) -> tuple[Finding]:
    return tuple(Finding(value) for value in malware_findings_context)


def findings_to_table(findings: tuple[Finding]) -> CommandResults:
    return CommandResults(
        outputs=[finding.to_summary_line() for finding in findings],
        outputs_prefix='FindingsTable'
    )


def main():
    try:
        malware_context = demisto.callingContext \
            .get('context', {}).get('ExecutionContext', {}).get('MalwareFinding', ())
        return_results(findings_to_table(get_findings(malware_context)))
    except Exception as ex:
        demisto.error(traceback.format_exc())  # print the traceback
        return_error(f'Failed to execute FindingsToTable. Error: {str(ex)}')


if __name__ == '__main__':
    main()
